name: Publish with Lerna

on:
  push:
    branches:
    - master

jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        # pulls all commits (needed for lerna / semantic release to correctly version) — see https://github.com/lerna/lerna/issues/2542
        fetch-depth: "0"
    - name: Git Identity
      run: |
        git config --global user.name '@lyhourchhen'
        git config --global user.email 'ukamilove66@gmail.com'
        git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
    - name: Fetch
      # see https://github.com/lerna/lerna/issues/2542
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Pulling
      run: git pull
    - name: Install dependencies
      run: yarn install --pure-lockfile
    - name: Authenticate with Registry
      run: |
          yarn logout
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
      env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish with Lerna
      run: yarn lerna publish --yes --message 'chore(release)'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




# name: Release CD
# on: [push]

# jobs:
#   release:
#     name: Run release
#     runs-on: ubuntu-18.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Setup Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           fetch-depth: "0"
#           registry-url: https://registry.npmjs.org/
#       - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
#       - name: Checkout back to master
#         run: git checkout master
#       - name: Install dependencies
#         run: yarn install --pure-lockfile && yarn run lerna bootstrap
#       - name: Setting registry
#         run: npm config set registry https://registry.npmjs.com
#       - name: Authenticate with Registry
#         run: |
#           yarn logout
#           echo "registry=http://registry.npmjs.org/" >> .npmrc
#           echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
#           npm whoami
#         env:
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#       - name: Publish with lerna
#         run: git stash && yarn lerna publish from-package --yes 
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        
