name: Release CD
on: [push]

jobs:
  release:
    name: Run release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Checkout back to master
        run: git checkout master
      - name: Install dependencies
        run: yarn install && yarn run lerna bootstrap
      - name: Setting registry
        run: npm config set registry https://registry.npmjs.com
      - name: Release
        run: npm whoami && yarn run lerna publish from-package --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
