name: Release CI
on: [push]

jobs:
  test-and-release:
    name: Run release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout back to master
        run: git checkout master
      - name: Install dependencies
        run: npm install && npm run lerna bootstrap
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run lerna publish from-package
