name: Publish with Lerna

on:
  push:
    branches:
      - master

jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Git Identity
        run: |
          git config --global user.name '@lyhourchhen'
          git config --global user.email 'ukamilove66@gmail.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - name: Fetch
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Pulling
        run: git pull
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@asurraa:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish with Lerna
        run: npm whoami && git stash && npx lerna publish from-package --exact --no-git-tag-version --no-push --yes --npm-tag=latest --force-publish=*
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
