name: Release CD
on: [push]

jobs:
  release:
    name: Run release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Checkout back to master
        run: git checkout master
      - name: Install dependencies
        run: yarn install && yarn run lerna bootstrap
      - name: Setting registry
        run: npm config set registry https://registry.npmjs.com
      - name: Authenticate with Registry
        run: |
          yarn logout
          # npm logout
          # echo "@apollo-elements:registry=http://registry.npmjs.org/" > .npmrc 
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami && npm whoami --registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: git stash && npx lerna publish from-package --yes --no-verify-access
